fixed error calling eq: incompatible types for comparison
full error:
500 internal server error
template: repo/graph/svgcontainer:12:43: executing "repo/graph/svgcontainer" at <eq $glyph.Glyph '.'>: error calling eq: incompatible types for comparison

This was caused by an _ symbol in the output of the git graph command. When coming across '.', go templates interprets the . character as per https://golang.org/pkg/text/template/, second paragraph: Execution of the template walks the structure and sets the cursor, represented by a period '.' and called "dot", to the value at the current location in the structure as execution proceeds.

Adding a \ eliminates interpretation and allows the code to proceed.