Make test work with different default branch config (#18038)
* Make test work with different default branch config

On a system configured with a different default branch name, doGitInitTestRepository
will create a repository with a branch named differently, and so further tests
would break:

  --- FAIL: TestGit/HTTP/PushCreate/SuccessfullyPushAndCreateTestRepository (0.02s)
      git_helper_for_declarative_test.go:167:
          	Error Trace:	git_helper_for_declarative_test.go:167
          	Error:      	Received unexpected error:
          	            	exit status 1 - error: src refspec master does not match any
          	            	error: failed to push some refs to 'http://127.0.0.1:3003/user2/repo-tmp-push-create-http.git'
          	Test:       	TestGit/HTTP/PushCreate/SuccessfullyPushAndCreateTestRepository
  git_test.go:587:
      	Error Trace:	git_test.go:587
      	Error:      	Received unexpected error:
      	            	repository does not exist [id: 0, uid: 0, owner_name: user2, name: repo-tmp-push-create-http]
      	Test:       	TestGit/HTTP/PushCreate

* Update integrations/git_helper_for_declarative_test.go

Co-authored-by: Lunny Xiao <xiaolunwen@gmail.com>
Co-authored-by: zeripath <art27@cantab.net>
Co-authored-by: 6543 <6543@obermui.de>